### PR TITLE
Rcd e

### PR DESCRIPTION
**Pull request by Emyrk**

### CODE REVIEW

**Comment by PaulBernier** [comment]
@Emyrk could you give us the context of this PR? What was the motivation and end purpose?
@WhoSoup we have removed wallet folder from this lib, I don't think we will be able to recover this PR, but we may need to port it to factom-walletd repo, if relevant.

**Comment by WhoSoup** [comment]
> @Emyrk could you give us the context of this PR? What was the motivation and end purpose?

RCD-e is the ethereum addresses that are needed for the factom<->ethereum gateway. PegNet also uses them for its gateway and right now, the pegnet project uses emyrk's fork as factom lib.

RCD-e isn't inside factomd yet since this would be a hard fork, so the PR likely would have just idled until then.

**Comment by PaulBernier** [comment]
Good to know this is beeing used, gives some confidence in the testing.
@Emyrk are you willing to help us make the extra push to get this merged into develop? By that I mean resolve conflicts and address potential review commets. It's totally fine to say no if don't want to, but we need to know if we need to re do that PR ourselves or not. Thank you.

**Comment by PaulBernier** [comment]
Sounds like we won't be able to move forward with this PR... I created an issue to track that feature request https://github.com/FactomProject/factom/issues/148

**Pull request closed without merging**
